
- hosts: PNAME
  any_errors_fatal: True
  gather_facts: no
  vars_files:
  - var_files/ENV/base_init
  - var_files/ENV/PNAME_init
  - var_files/ENV/PNAME_host
  - var_files/ENV/PNAME_guest
  - var_files/ENV/PNAME_exchange
  roles:
  - { role: "mysql_uninstall", when: "( 'host' in deploy_roles and ansible_ssh_host in host['mysql']['ips'] and host['mysql']['enable'] == True and deploy_mode == 'uninstall' ) or ( 'guest' in deploy_roles and ansible_ssh_host in guest['mysql']['ips'] and guest['mysql']['enable'] == True and deploy_mode == 'uninstall' )" }
  - { role: "fateflow_uninstall", when: "( 'host' in deploy_roles and ansible_ssh_host in host['fate_flow']['ips'] and host['fate_flow']['enable'] == True and deploy_mode == 'uninstall'  ) or ( 'guest' in deploy_roles and ansible_ssh_host in guest['fate_flow']['ips'] and guest['fate_flow']['enable'] == True and deploy_mode == 'uninstall' )" }
  - { role: "fateboard_uninstall", when: "( 'host' in deploy_roles and ansible_ssh_host in host['fateboard']['ips'] and host['fateboard']['enable'] == True and deploy_mode == 'uninstall' ) or ( 'guest' in deploy_roles and ansible_ssh_host in guest['fateboard']['ips'] and guest['fateboard']['enable'] == True and deploy_mode == 'uninstall' )" }
