- name: "Copy({{deploy_mode}}): {{pbase}}/{{pname}}/sql/create-eggroll-meta-tables.sql"
  copy:
    src: "create-eggroll-meta-tables.sql"
    dest: "{{pbase}}/{{pname}}/sql/create-eggroll-meta-tables.sql"

- when: "ansible_ssh_host in clustermanager.get('ips',[]) and clustermanager.get('enable', False) == True"
  block:
  - name: "update({{deploy_mode}}): {{tbase}}/check.py"
    template: src=templates/check.py.jinja dest={{tbase}}/check.py
    vars:
      admin_user: "{{mysql.get('user','root')}}"
      admin_passwd: "{{mysql.get('passwd','fate')}}"
      db_name: "{{eggroll.get('dbname','eggroll_meta')}}"
      db_host: "{{db.get('ips',[])[0]}}"
      db_port: "{{db.get('port',3306)}}"

  - name: "commit({{deploy_mode}}): check.py"
    shell: "{{cbase}}/miniconda3/bin/python {{tbase}}/check.py"
    register: mysql_load

  - debug: var=mysql_load.get('stdout_lines')
  
  - name: "update({{deploy_mode}}): {{tbase}}/load.py"
    template: src=templates/load.py.jinja dest={{tbase}}/db_create.py
    vars:
      fname: "{{pbase}}/{{pname}}/sql/create-eggroll-meta-tables.sql"
      db_name: "{{eggroll.get('dbname','eggroll_meta')}}"
      db_host: "{{db.get('ips',[])[0]}}"
      db_port: "{{db.get('port',3306)}}"
      admin_user: "{{mysql.get('user','root')}}"
      admin_passwd: "{{mysql.get('passwd','fate')}}"

  - name: "commit({{deploy_mode}}): db_create.py"
    shell: "{{cbase}}/miniconda3/bin/python {{tbase}}/db_create.py"
    register: mysql_load

  - debug: var=mysql_load.get('stderr_lines')
  - debug: var=mysql_load.get('stdout_lines')


  - name: "update({{deploy_mode}}): {{tbase}}/conn.py"
    template: src=templates/conn.py.jinja dest={{tbase}}/cluster_conn.py
    vars:
      rrole: clustermanager
      rip: "{{clustermanager.get('ips',[])[0]}}"
      rport: "{{clustermanager.get('port')}}"
      admin_user: "{{mysql.get('user','root')}}"
      admin_passwd: "{{mysql.get('passwd','fate')}}"
      db_name: "{{eggroll.get('dbname','eggroll_meta')}}"
      db_host: "{{db.get('ips',[])[0]}}"
      db_port: "{{db.get('port',3306)}}"
      db_user: "{{db.get('dbuser','fate')}}"
      db_passwd: "{{db.get('dbpasswd','fate')}}"

  - name: "commit({{deploy_mode}}): cluster_conn.py"
    shell: "{{cbase}}/miniconda3/bin/python {{tbase}}/cluster_conn.py"
    register: mysql_load

  - debug: var=mysql_load.get('stderr_lines')
  - debug: var=mysql_load.get('stdout_lines')

- when: "ansible_ssh_host in nodemanager.get('ips',[]) and nodemanager.get('enable', False) == True"
  block:
  - name: "update({{deploy_mode}}): {{tbase}}/node_conn.py"
    template: src=templates/conn.py.jinja dest={{tbase}}/node_conn.py
    vars:
      rrole: nodemanager
      rip: "{{item}}"
      rport: "{{nodemanager.get('port')}}"
      admin_user: "{{mysql.get('user','root')}}"
      admin_passwd: "{{mysql.get('passwd','fate')}}"
      db_name: "{{eggroll.get('dbname','eggroll_meta')}}"
      db_host: "{{db.get('ips',[])[0]}}"
      db_port: "{{db.get('port',3306)}}"
      db_user: "{{db.get('dbuser','fate')}}"
      db_passwd: "{{db.get('dbpasswd','fate')}}"
    with_items:
    - "{{nodemanager.get('ips',[])}}"

  - name: "commit({{deploy_mode}}): node_conn.py"
    shell: "{{cbase}}/miniconda3/bin/python {{tbase}}/node_conn.py"
    register: mysql_load

  - debug: var=mysql_load.get('stderr_lines')
  - debug: var=mysql_load.get('stdout_lines')


