- name: Stop fateboard service
  shell: /bin/bash {{cbase}}/supervisord/service.sh stop {{pname}}-fateboard
  ignore_errors: yes

- name: Remove supervisord files
  file: path={{item}} state=absent
  with_items:
  - "{{cbase}}/supervisord/supervisord.d/{{pname}}-fateboard.conf"

- name: Update fateboard service
  shell: /bin/bash {{cbase}}/supervisord/service.sh update {{pname}}-fateboard
  ignore_errors: yes

- name: Remove fateboard deployfiles
  file: path={{item}} state=absent
  with_items:
  - "{{pbase}}/{{pname}}/fateboard"

