- include_tasks: install.yml
  when: deploy_mode in [ 'deploy', 'install' ]

- include_vars: "host_vars.yml"
  when: deploy_mode in [ 'deploy', 'config' ] and 'host' in deploy_roles

- include_tasks: load.yml
  when: deploy_mode in [ 'deploy', 'config' ] and 'host' in deploy_roles

- include_tasks: config.yml
  when: "deploy_mode in [ 'deploy', 'config' ] and 'host' in deploy_roles and deploy_role == 'host' and ansible_ssh_host in fate_flow.get('ips',[]) and fate_flow.get('enable', False) == True"

- include_tasks: config_for_eggroll.yml
  when: "deploy_mode in [ 'deploy', 'config' ] and 'host' in deploy_roles and deploy_role == 'host' and ansible_ssh_host in nodemanager.get('ips',[]) and nodemanager.get('enable', False) == True"

- include_vars: "guest_vars.yml"
  when: deploy_mode in [ 'deploy', 'config' ] and 'guest' in deploy_roles

- include_tasks: load.yml
  when: deploy_mode in [ 'deploy', 'config' ] and 'guest' in deploy_roles

- include_tasks: config.yml
  when: "deploy_mode in [ 'deploy', 'config' ] and 'guest' in deploy_roles and deploy_role == 'guest' and ansible_ssh_host in fate_flow.get('ips',[]) and fate_flow.get('enable', False) == True"

- include_tasks: config_for_eggroll.yml
  when: "deploy_mode in [ 'deploy', 'config' ] and 'guest' in deploy_roles and deploy_role == 'guest' and ansible_ssh_host in nodemanager.get('ips',[]) and nodemanager.get('enable', False) == True"

