- include_tasks: install.yml
  when: deploy_mode in [ 'deploy', 'install' ]

- include_vars: "host_vars.yml"
  when: deploy_mode in [ 'deploy', 'config' ] and 'host' in deploy_roles

- include_tasks: config.yml
  when: deploy_mode in [ 'deploy', 'config' ] and 'host' in deploy_roles and ansible_ssh_host in db.get('ips',[])

- include_vars: "guest_vars.yml"
  when: deploy_mode in [ 'deploy', 'config' ] and 'guest' in deploy_roles

- include_tasks: config.yml
  when: deploy_mode in [ 'deploy', 'config' ] and 'guest' in deploy_roles and ansible_ssh_host in db.get('ips',[])

- include_tasks: load.yml
  when: deploy_mode in [ 'deploy', 'config' ]
